- hosts: master
  become: yes
  tasks:
    - name: Add Proxmox Gpg Keyring
      ansible.builtin.apt_key:
        url: http://download.proxmox.com/debian/proxmox-release-bookworm.gpg
        keyring: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
    - name: Add proxmox repository into sources list
      ansible.builtin.apt_repository:
        repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
        state: present
        filename: pve-install-repo
    - name: Remove proxmox enterprise repository in sources list
      ansible.builtin.apt_repository:
        repo: deb https://enterprise.proxmox.com/debian/pve bookworm InRelease
        state: absent
        filename: pve-enterprise
    - name: Apt update and full upgrade
      ansible.builtin.apt:
        upgrade: "full"
    - name: Install the package "proxmox-ve"
      ansible.builtin.apt:
        name: proxmox-ve
        state: present
